{% set name = "metawrap" %}
{% set data = load_setup_py_data(setup_file="setup.py") %}
{% set version = data.get("version") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/jakirkham/metawrap
  git_rev: HEAD

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  source_files:
    - tests

  imports:
    - metawrap

  commands:
    - python -m unittest discover -s .

about:
  home: http://github.com/jakirkham/metawrap
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A collection of wrappers for functions and classes.
  doc_url: https://metawrap.readthedocs.io/
  dev_url: http://github.com/jakirkham/metawrap

extra:
  recipe-maintainers:
    - jakirkham
