travis:
  secure:
    BINSTAR_TOKEN: JvB7AndhLWqE9vTsNtoGydIvTVN/FQXfQQsO17FNHNok2jLLvnoDhm+Ytd7VnYmp677tknEaVvIWbVJQxeeQjOz2t2KgyzFvelDBovAPrJHZ03S9Y2DBmKwkH5k7gsE1QAYhCRTZoFMGZQl2VvLGwWhIJK4tU1WIMcyOXwQl2L9CRJ6AC++nDiSMG4hDvrl42IIOnv+23Ycy/rByEcq9sHhUnt7PHlG6ek/ctHkhYVwup3A/Ts1PZ2Vya0vsrlih+9hO9TNnXpMgp6AVeDqcUZugg5ZEJMmm2uQgy7+sezx25Aani7qnMVbNchQNdnCOsuojHlj86bECaB+qyKvwxI57j7mL5UgxjatClFTux6SRVuAi3vM/YfPJNDfvnzvmn3tLMZKL+BgxMv45vnqIlxBxaW9c4E+0VS6GP4AtNj2O4/J8P9XMJjBpArXnXXx5gEw6fwbj6eHMHy7noBpV4OoFuOCYNK4IWo7e0pdkEk7thLV9n6vZFVtn84W9eeYBnA0hVBFHHBrAzrFZE+LTU47QfMXoY9ZYMB40O9nc3D2R9vqtXaPEGp1YN0v7DAfKcXhjX1zHRWnWnDToQZ9FPxaT7MeKESBbWOxChe9FuEq6OS+IVVsi71VK8btIy9lvgDyjG4Ktefbo6OCrq/fIy8gRfFYxupi6bTz+L0L5noU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
